- hosts: all
  vars:
    destination: /opt/pSSID-database
    repository: https://github.com/UMNET-perfSONAR/pSSID-database

  roles:
    - geerlingguy.docker

  tasks:
    - name: clone pSSID-database from the git server
      git:
        dest: "{{ destination }}"
        repo: "{{ repository }}"
        force: true
    - name: generate .env file and copy to target
      copy:
        src: ./.env
        dest: "{{ destination }}/.env"
        force: true
        decrypt: true
    - name: run `docker-compose down -v` to reset any volumes (perhaps unnecessary)
      command:
        chdir: "{{ destination }}"
        cmd: docker-compose down -v
    - name: bring up the stack
      command:
        chdir: "{{ destination }}"
        cmd: docker-compose up -d

